//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_MVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StoreDbEntities : DbContext
    {
        public StoreDbEntities()
            : base("name=StoreDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategories> tblCategories { get; set; }
        public virtual DbSet<tblOrderDetails> tblOrderDetails { get; set; }
        public virtual DbSet<tblOrders> tblOrders { get; set; }
        public virtual DbSet<tblPages> tblPages { get; set; }
        public virtual DbSet<tblPayOrder> tblPayOrder { get; set; }
        public virtual DbSet<tblProducts> tblProducts { get; set; }
        public virtual DbSet<tblRoles> tblRoles { get; set; }
        public virtual DbSet<tblSidebar> tblSidebar { get; set; }
        public virtual DbSet<tblUserRoles> tblUserRoles { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblCoordinateRest> tblCoordinateRest { get; set; }
        public virtual DbSet<tblRestaurant> tblRestaurant { get; set; }
    }
}
