//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategories
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public Nullable<int> Sorting { get; set; }
    }
}
