//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducts
    {
        public int Id { get; set; }
        public Nullable<int> RestarauntId { get; set; }
        public string RestarauntName { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string ImageName { get; set; }
    }
}
