//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayOrder
    {
        public int Id { get; set; }
        public Nullable<int> Numbercart { get; set; }
        public Nullable<int> CVV { get; set; }
        public string DateTime { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrderDetailsId { get; set; }
    }
}
